import Head from "next/head";
import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="favicon.ico"  />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, maxime sunt. Consequatur architecto cupiditate quasi quae repudiandae corporis, et dolores perferendis sunt voluptate laudantium nobis ratione fugit. Quisquam, tenetur voluptates.
        </p>
      </main>
    </>
  )
}

export default Home